import base64
import io
import json
import os
import re
import uuid
from typing import Annotated, Any, Dict, List, Literal, Optional, Union
from datetime import datetime
from pathlib import Path

import easyocr
import ollama
from fastapi import FastAPI
from groq import Groq
from PIL import Image, UnidentifiedImageError
from pydantic import BaseModel, Field, ValidationError

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY", ""))

OLLAMA_MODEL = "gemma4:latest"
GROQ_MODEL = "openai/gpt-oss-120b"
GROQ_WITH_IMAGE_MODEL = "qwen/qwen3.8-27b"
MAX_ACTIONS = 20
MAX_OCR_BLOCKS = 200

app = FastAPI(
    title="Stateless Browser Agent",
    version="1.0.0",
)


class BoundingBox(BaseModel):
    x: float
    y: float
    width: float
    height: float


class DOMElement(BaseModel):
    id: str = Field(min_length=1, max_length=300)
    tag: Optional[str] = None
    type: Optional[str] = None
    label: Optional[str] = None
    aria_label: Optional[str] = None
    placeholder: Optional[str] = None
    name: Optional[str] = None
    role: Optional[str] = None
    text: Optional[str] = None
    masked_value: Optional[str] = None
    href: Optional[str] = None
    disabled: Optional[bool] = False
    checked: Optional[bool] = None
    selected: Optional[bool] = None
    visible: Optional[bool] = True
    bounding_box: Optional[BoundingBox] = None
    attributes: Optional[Dict[str, Any]] = None


class BrowserContext(BaseModel):
    url: Optional[str] = None
    title: Optional[str] = None
    viewport_width: Optional[int] = None
    viewport_height: Optional[int] = None
    elements: List[DOMElement] = Field(default_factory=list)


class AvailableSecret(BaseModel):
    key: str = Field(min_length=1, max_length=200)
    description: Optional[str] = Field(default=None, max_length=300)
    category: Literal[
        "email",
        "username",
        "password",
        "api_key",
        "phone",
        "address",
        "otp",
        "name",
        "other",
    ] = "other"


class UserInput(BaseModel):
    key: str = Field(min_length=1, max_length=200)
    value: str = Field(max_length=5000)


# Added to capture historical assistant messages sent back by the client
class MessageHistory(BaseModel):
    role: Literal["assistant", "system"] = "assistant"
    message: str = Field(max_length=2000)


class AgentRequest(BaseModel):
    request_id: Optional[str] = None
    query: str = Field(min_length=1, max_length=10000)
    browser: BrowserContext
    available_secrets: List[AvailableSecret] = Field(default_factory=list)
    user_inputs: List[UserInput] = Field(default_factory=list)
    previous_messages: List[MessageHistory] = Field(
        default_factory=list,
        description="List of prior messages generated by the agent during this workflow.",
    )
    screenshot_base64: Optional[str] = None


class ClickAction(BaseModel):
    type: Literal["click"]
    element_id: str
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class MoveAction(BaseModel):
    type: Literal["move"]
    element_id: str
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class TypeTextAction(BaseModel):
    type: Literal["type_text"]
    element_id: str
    text: str = Field(max_length=5000)
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class TypeSecretAction(BaseModel):
    type: Literal["type_secret"]
    element_id: str
    secret_key: str
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class KeyAction(BaseModel):
    type: Literal["key"]
    key: Literal[
        "ENTER",
        "TAB",
        "ESCAPE",
        "BACKSPACE",
        "ARROWDOWN",
        "ARROWUP",
        "ARROWLEFT",
        "ARROWRIGHT",
        "HOME",
        "END",
        "SPACE",
    ]
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class ScrollAction(BaseModel):
    type: Literal["scroll"]
    direction: Literal["up", "down", "left", "right"]
    amount: int = Field(default=500, ge=1, le=5000)
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class WaitAction(BaseModel):
    type: Literal["wait"]
    milliseconds: int = Field(default=1000, ge=0, le=30000)
    reason: Optional[str] = None


class RequestScreenshotAction(BaseModel):
    type: Literal["request_screenshot"]
    reason: str = Field(min_length=1, max_length=1000)


class RequestUserInputAction(BaseModel):
    type: Literal["request_user_input"]
    field_name: str = Field(min_length=1, max_length=200)
    label: str = Field(min_length=1, max_length=300)
    description: Optional[str] = Field(default=None, max_length=1000)
    suggested_input_type: Literal[
        "text", "number", "email", "phone", "date", "password"
    ] = "text"


Action = Annotated[
    Union[
        ClickAction,
        MoveAction,
        TypeTextAction,
        TypeSecretAction,
        KeyAction,
        ScrollAction,
        WaitAction,
        RequestScreenshotAction,
        RequestUserInputAction,
    ],
    Field(discriminator="type"),
]


class AgentPlan(BaseModel):
    status: Literal[
        "actions_ready",
        "screenshot_required",
        "user_input_required",
    ]
    message: str = Field(
        ...,
        description="User-facing message to display directly in the chat interface.",
        min_length=1,
        max_length=2000,
    )
    reasoning_summary: str = Field(min_length=1, max_length=1500)
    actions: List[Action] = Field(min_length=0, max_length=MAX_ACTIONS)


class AgentResponse(BaseModel):
    request_id: str
    status: Literal[
        "actions_ready",
        "screenshot_required",
        "user_input_required",
        "error",
    ]
    message: Optional[str] = None
    reasoning_summary: str
    actions: List[Action]
    error: Optional[str] = None


SYSTEM_PROMPT = """
You are a stateless browser automation planner.

You receive:
1. A user query.
2. Browser DOM metadata.
3. Available local secret aliases.
4. Optional non-secret user inputs.
5. Previous response messages: A chronological log of messages you previously returned to the user in this workflow session.

CRITICAL INSTRUCTIONS ON PREVIOUS RESPONSE MESSAGES:
- Use the `previous_messages` list to determine what stage of the execution workflow you are currently in.
- If you previously requested user input (`user_input_required`) or a screenshot (`screenshot_required`), check whether the required information or DOM changes are now present in the incoming payload.
- Do NOT repeat questions, prompts, or requests for information that have already been answered or provided in `user_inputs` or the current DOM context.
- Use this historical sequence to track multi-step multi-page workflows without maintaining server-side state.

Secret values are never available to you. You only receive secret aliases.

You must never invent a secret_key, guess a secret value, reconstruct a secret value, or place a secret value in type_text.

To use a locally stored secret, return:

{
    "type": "type_secret",
    "element_id": "existing_dom_element_id",
    "secret_key": "existing_secret_key",
    "confidence": 0.95
}

The browser resolves secret_key locally.

Only use element_id values that actually exist in the provided DOM.

Never invent an element ID.

Prefer DOM information such as label, aria_label, placeholder, role, name, type, and visible text before using OCR.

If the DOM does not contain enough information to identify the requested target and visual information is necessary, return:

{
    "status": "screenshot_required",
    "reasoning_summary": "short explanation",
    "actions": [
        {
            "type": "request_screenshot",
            "reason": "why visual information is needed"
        }
    ]
}

Do not request a screenshot if the DOM already contains enough information.

If required information is not in the user query, user_inputs, or represented by an appropriate secret alias, return:

{
    "status": "user_input_required",
    "reasoning_summary": "short explanation",
    "actions": [
        {
            "type": "request_user_input",
            "field_name": "required_value",
            "label": "Required value",
            "description": "what the user needs to provide",
            "suggested_input_type": "text"
        }
    ]
}

Supported suggested_input_type:
"text",
"number",
"email",
"phone",
"date",
"password"

Supported actions:

{
    "type": "click",
    "element_id": "...",
    "confidence": 0.95
}

{
    "type": "move",
    "element_id": "...",
    "confidence": 0.95
}

{
    "type": "type_text",
    "element_id": "...",
    "text": "...",
    "confidence": 0.95
}

{
    "type": "type_secret",
    "element_id": "...",
    "secret_key": "...",
    "confidence": 0.95
}

{
    "type": "key",
    "key": "ENTER",
    "confidence": 0.95
}

{
    "type": "scroll",
    "direction": "down",
    "amount": 500,
    "confidence": 0.95
}

{
    "type": "wait",
    "milliseconds": 1000
}

If an element contains allowed_secret_categories, only use a secret with a compatible category.

Return only valid JSON with no markdown or surrounding text.

The output format is:

{
    "status": "actions_ready | screenshot_required | user_input_required",
    "message": "A clear, natural, human-friendly response or explanation to display to the user in the chat window.",
    "reasoning_summary": "Short internal technical explanation of your decision",
    "actions": []
}
"""


def prepare_element(element: DOMElement) -> Dict[str, Any]:
    raw_result = {
        "id": element.id,
        "tag": element.tag,
        "type": element.type,
        "label": element.label,
        "aria_label": element.aria_label,
        "placeholder": element.placeholder,
        "name": element.name,
        "role": element.role,
        "text": element.text,
        "masked_value": element.masked_value,
        "href": element.href,
        "disabled": element.disabled,
        "checked": element.checked,
        "selected": element.selected,
        "visible": element.visible,
    }

    result = {
        key: value
        for key, value in raw_result.items()
        if value is not None and value != ""
    }

    if element.bounding_box is not None:
        result["bounding_box"] = element.bounding_box.model_dump()

    return result


def prepare_browser_context(browser: BrowserContext) -> Dict[str, Any]:
    return {
        "url": browser.url,
        "title": browser.title,
        "viewport": {
            "width": browser.viewport_width,
            "height": browser.viewport_height,
        },
        "elements": [
            prepare_element(element)
            for element in browser.elements
            if element.visible
        ],
    }


def normalize_base64_image(image_data: str) -> Optional[Dict[str, str]]:
    if not image_data or not isinstance(image_data, str):
        return None

    mime_type = "image/png"

    if "," in image_data:
        header, image_data = image_data.split(",", 1)
        if "data:" in header and ";base64" in header:
            mime_type = header.split(";")[0].replace("data:", "")

    image_data = image_data.strip().replace("\n", "").replace("\r", "")

    missing_padding = len(image_data) % 4
    if missing_padding:
        image_data += "=" * (4 - missing_padding)

    try:
        decoded_image = base64.b64decode(image_data, validate=True)
    except Exception as e:
        print("Invalid Base64 image:", e)
        return None

    received_dir = Path("received")
    received_dir.mkdir(parents=True, exist_ok=True)

    extension_map = {
        "image/jpeg": ".jpg",
        "image/jpg": ".jpg",
        "image/png": ".png",
        "image/gif": ".gif",
        "image/webp": ".webp",
        "image/bmp": ".bmp",
        "image/tiff": ".tiff",
    }

    extension = extension_map.get(mime_type.lower(), ".png")

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    image_path = received_dir / f"{timestamp}{extension}"

    try:
        image_path.write_bytes(decoded_image)
        print(f"Image saved: {image_path}")
    except Exception as e:
        print("Failed to save image:", e)
        return None

    return {
        "base64": image_data,
        "mime_type": mime_type,
    }

def extract_json(text: str) -> Dict[str, Any]:
    text = text.strip()

    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?", "", text, flags=re.IGNORECASE)
        text = re.sub(r"```$", "", text).strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    start = text.find("{")
    end = text.rfind("}")

    if start != -1 and end != -1:
        return json.loads(text[start:end + 1])

    raise ValueError("Model did not return valid JSON")


def ask_model(
        request: AgentRequest,
        browser_context: Dict[str, Any],
        image: Optional[List[Dict[str, Any]]] = None,
) -> AgentPlan:

    payload = {
        "user_query": request.query,
        "browser_dom": browser_context,
        "available_secrets": [
            {
                "key": secret.key,
                "category": secret.category,
                "description": secret.description,
            }
            for secret in request.available_secrets
        ],
        "user_inputs": [
            {
                "key": user_input.key,
                "value": user_input.value,
            }
            for user_input in request.user_inputs
        ],
        "previous_messages": [
            {
                "role": msg.role,
                "message": msg.message,
            }
            for msg in request.previous_messages
        ],
    }

    normalized_images = []

    if image:
        for image_item in image:
            if isinstance(image_item, dict) and "base64" in image_item:
                normalized_images.append(image_item)
            elif isinstance(image_item, str):
                normalized = normalize_base64_image(image_item)
                if normalized:
                    normalized_images.append(normalized)

    return generate_agent_plan(
        payload=payload,
        images=normalized_images or None,
    )


def generate_agent_plan(
        payload: dict,
        images: Optional[List[Dict[str, str]]] = None,
) -> AgentPlan:

    try:
        if images:
            content = [
                {
                    "type": "text",
                    "text": json.dumps(payload, ensure_ascii=False),
                }
            ]

            for img in images:
                content.append(
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:{img['mime_type']};base64,{img['base64']}"
                        },
                    }
                )

            model = GROQ_WITH_IMAGE_MODEL
        else:
            content = json.dumps(payload, ensure_ascii=False)
            model = GROQ_MODEL

        completion = groq_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": content},
            ],
            temperature=0.05,
            response_format={"type": "json_object"},
        )

        print(
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": content},
            ],
            "\n"*5
        )

        response_content = completion.choices[0].message.content
        parsed = extract_json(response_content)
        return AgentPlan.model_validate(parsed)

    except Exception as e:
        print("Groq Exception:", e)

        ollama_message = {
            "role": "user",
            "content": json.dumps(payload, ensure_ascii=False),
        }

        if images:
            ollama_message["images"] = [img["base64"] for img in images]

        response = ollama.chat(
            model=OLLAMA_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                ollama_message,
            ],
            format="json",
            options={
                "temperature": 0.05,
                "num_predict": 2000,
            },
        )

        response_content = response["message"]["content"]
        parsed = extract_json(response_content)
        return AgentPlan.model_validate(parsed)


def validate_plan(
        plan: AgentPlan,
        request: AgentRequest,
) -> AgentPlan:
    element_map = {element.id: element for element in request.browser.elements}
    secret_map = {secret.key: secret for secret in request.available_secrets}

    screenshot_requests = 0
    user_input_requests = 0

    for action in plan.actions:
        if isinstance(
                action,
                (ClickAction, MoveAction, TypeTextAction, TypeSecretAction),
        ):
            if action.element_id not in element_map:
                raise ValueError(f"Invalid element_id: {action.element_id}")

            element = element_map[action.element_id]

            if not element.visible:
                raise ValueError(f"Invisible element: {action.element_id}")

            if element.disabled:
                raise ValueError(f"Disabled element: {action.element_id}")

        if isinstance(action, TypeSecretAction):
            if action.secret_key not in secret_map:
                raise ValueError(f"Invalid secret_key: {action.secret_key}")

        if isinstance(action, RequestScreenshotAction):
            screenshot_requests += 1

        if isinstance(action, RequestUserInputAction):
            user_input_requests += 1

    if plan.status == "screenshot_required":
        if screenshot_requests != 1:
            raise ValueError(
                "screenshot_required requires exactly one request_screenshot action"
            )

    elif plan.status == "user_input_required":
        if user_input_requests < 1:
            raise ValueError(
                "user_input_required requires at least one request_user_input action"
            )

    elif plan.status == "actions_ready":
        if screenshot_requests > 0:
            raise ValueError("actions_ready cannot contain request_screenshot")

        if user_input_requests > 0:
            raise ValueError("actions_ready cannot contain request_user_input")

    return plan


@app.post("/agent", response_model=AgentResponse)
def run_agent(request: AgentRequest):
    request_id = request.request_id or str(uuid.uuid4())

    try:
        browser_context = prepare_browser_context(request.browser)

        image = None
        if request.screenshot_base64:
            normalized = normalize_base64_image(request.screenshot_base64)
            if normalized:
                image = [normalized]

        plan = ask_model(
            request=request,
            browser_context=browser_context,
            image=image,
        )

        validated_plan = validate_plan(
            plan=plan,
            request=request,
        )

        print(
            AgentResponse(
                request_id=request_id,
                status=validated_plan.status,
                message=validated_plan.message,
                reasoning_summary=validated_plan.reasoning_summary,
                actions=validated_plan.actions,
                error=None,
            )
        )

        return AgentResponse(
            request_id=request_id,
            status=validated_plan.status,
            message=validated_plan.message,
            reasoning_summary=validated_plan.reasoning_summary,
            actions=validated_plan.actions,
            error=None,
        )

    except ValidationError as error:
        return AgentResponse(
            request_id=request_id,
            status="error",
            reasoning_summary="Model output failed Pydantic validation.",
            actions=[],
            error=str(error),
        )

    except Exception as error:
        return AgentResponse(
            request_id=request_id,
            status="error",
            reasoning_summary="Agent processing failed.",
            actions=[],
            error=str(error),
        )


@app.get("/health")
def health():
    return {
        "status": "ok",
        "model": OLLAMA_MODEL,
        "architecture": "stateless",
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app:app",
        host="0.0.0.0",
        port=8000,
        reload=False,
    )