import base64
import io
import json
import os
import re
import uuid
from typing import Annotated, Any, Dict, List, Literal, Optional, Union
from datetime import datetime
from pathlib import Path

import easyocr
import ollama
from fastapi import FastAPI
from groq import Groq
from PIL import Image, UnidentifiedImageError
from pydantic import BaseModel, Field, ValidationError

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY", ""))

OLLAMA_MODEL = "gemma4:latest"
GROQ_MODEL = "openai/gpt-oss-120b"
GROQ_WITH_IMAGE_MODEL = "qwen/qwen3.8-27b"
MAX_ACTIONS = 20
MAX_OCR_BLOCKS = 200

app = FastAPI(
    title="Stateless Browser Agent",
    version="1.0.0",
)


class BoundingBox(BaseModel):
    x: float
    y: float
    width: float
    height: float


class DOMElement(BaseModel):
    id: str = Field(min_length=1, max_length=300)
    tag: Optional[str] = None
    type: Optional[str] = None
    label: Optional[str] = None
    aria_label: Optional[str] = None
    placeholder: Optional[str] = None
    name: Optional[str] = None
    role: Optional[str] = None
    text: Optional[str] = None
    masked_value: Optional[str] = None
    href: Optional[str] = None
    disabled: Optional[bool] = False
    checked: Optional[bool] = None
    selected: Optional[bool] = None
    visible: Optional[bool] = True
    bounding_box: Optional[BoundingBox] = None
    attributes: Optional[Dict[str, Any]] = None


class BrowserContext(BaseModel):
    url: Optional[str] = None
    title: Optional[str] = None
    viewport_width: Optional[int] = None
    viewport_height: Optional[int] = None
    elements: List[DOMElement] = Field(default_factory=list)


class AvailableSecret(BaseModel):
    key: str = Field(min_length=1, max_length=200)
    description: Optional[str] = Field(default=None, max_length=300)
    category: Literal[
        "email",
        "username",
        "password",
        "api_key",
        "phone",
        "address",
        "otp",
        "name",
        "other",
    ] = "other"


class UserInput(BaseModel):
    key: str = Field(min_length=1, max_length=200)
    value: str = Field(max_length=5000)


# Added to capture historical assistant messages sent back by the client
class MessageHistory(BaseModel):
    role: Literal["assistant", "system"] = "assistant"
    message: str = Field(max_length=2000)


class AgentRequest(BaseModel):
    request_id: Optional[str] = None
    query: str = Field(min_length=1, max_length=10000)
    browser: BrowserContext
    available_secrets: List[AvailableSecret] = Field(default_factory=list)
    user_inputs: List[UserInput] = Field(default_factory=list)
    previous_messages: List[MessageHistory] = Field(
        default_factory=list,
        description="List of prior messages generated by the agent during this workflow.",
    )
    screenshot_base64: Optional[str] = None


class ClickAction(BaseModel):
    type: Literal["click"]
    element_id: str
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class MoveAction(BaseModel):
    type: Literal["move"]
    element_id: str
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class TypeTextAction(BaseModel):
    type: Literal["type_text"]
    element_id: str
    text: str = Field(max_length=5000)
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class TypeSecretAction(BaseModel):
    type: Literal["type_secret"]
    element_id: str
    secret_key: str
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class KeyAction(BaseModel):
    type: Literal["key"]
    key: Literal[
        "ENTER",
        "TAB",
        "ESCAPE",
        "BACKSPACE",
        "ARROWDOWN",
        "ARROWUP",
        "ARROWLEFT",
        "ARROWRIGHT",
        "HOME",
        "END",
        "SPACE",
    ]
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class ScrollAction(BaseModel):
    type: Literal["scroll"]
    direction: Literal["up", "down", "left", "right"]
    amount: int = Field(default=500, ge=1, le=5000)
    confidence: float = Field(ge=0.0, le=1.0)
    reason: Optional[str] = None


class WaitAction(BaseModel):
    type: Literal["wait"]
    milliseconds: int = Field(default=1000, ge=0, le=30000)
    reason: Optional[str] = None


class RequestScreenshotAction(BaseModel):
    type: Literal["request_screenshot"]
    reason: str = Field(min_length=1, max_length=1000)


class RequestUserInputAction(BaseModel):
    type: Literal["request_user_input"]
    field_name: str = Field(min_length=1, max_length=200)
    label: str = Field(min_length=1, max_length=300)
    description: Optional[str] = Field(default=None, max_length=1000)
    suggested_input_type: Literal[
        "text", "number", "email", "phone", "date", "password"
    ] = "text"


Action = Annotated[
    Union[
        ClickAction,
        MoveAction,
        TypeTextAction,
        TypeSecretAction,
        KeyAction,
        ScrollAction,
        WaitAction,
        RequestScreenshotAction,
        RequestUserInputAction,
    ],
    Field(discriminator="type"),
]


class AgentPlan(BaseModel):
    status: Literal[
        "actions_ready",
        "screenshot_required",
        "user_input_required",
    ]
    message: str = Field(
        ...,
        description="User-facing message to display directly in the chat interface.",
        min_length=1,
        max_length=2000,
    )
    reasoning_summary: str = Field(min_length=1, max_length=1500)
    actions: List[Action] = Field(min_length=0, max_length=MAX_ACTIONS)


class AgentResponse(BaseModel):
    request_id: str
    status: Literal[
        "actions_ready",
        "screenshot_required",
        "user_input_required",
        "error",
    ]
    message: Optional[str] = None
    reasoning_summary: str
    actions: List[Action]
    error: Optional[str] = None


SYSTEM_PROMPT = """
You are an autonomous browser automation agent and task executor.

Your primary responsibility is to understand the user's intent, inspect the provided browser DOM, reason about what needs to be done, and execute the task through browser actions.

You are NOT merely an action generator. You must first understand WHAT the user wants to accomplish and then determine HOW to accomplish it.

You receive:

1. A user query.
2. Browser DOM metadata.
3. Available local secret aliases.
4. Optional non-secret user inputs.
5. Previous response messages:
   A chronological log of messages you previously returned to the user in this workflow session.

==================================================
CORE AUTONOMOUS BEHAVIOR
==================================================

HARD DECISION PRECEDENCE (MUST FOLLOW)

Apply these rules before considering `user_input_required`:

1. If the page contains a quiz, test, assessment, assignment, MCQ, true/false
   question, matching question, numeric problem, or factual questionnaire,
   solve it yourself and return `actions_ready`.
2. The presence of two or more answer options is NEVER evidence that user input
   is required. Those options are inputs to your reasoning, not choices to send
   back to the user.
3. For an academic or factual question, make the best-supported selection using
   the question, choices, page context, and your knowledge. Do not require
   certainty. Choose the most likely answer even when confidence is below 1.0.
4. `user_input_required` is forbidden for requests whose goal is to answer,
   solve, complete, choose, or fill quiz/test/assessment questions.
5. An instruction such as "do not submit" limits only the final submission
   action. It does not prevent selecting, typing, or changing answers.

Before returning `user_input_required`, perform this mandatory self-check:

- Is this an academic, factual, logical, mathematical, or knowledge question?
- Are candidate answers visible in the DOM?
- Can I rank the candidates using reasoning or general knowledge?

If any answer is yes, do NOT request user input. Return `actions_ready` with the
best answer action instead.

You must act autonomously whenever the requested task can be completed using:

- The user's query.
- Information visible in the DOM.
- Information available through the browser/page.
- General knowledge and reasoning.
- Information that can be inferred from the page.
- Previously provided user inputs.
- Appropriate locally stored secret aliases.

Do NOT unnecessarily ask the user for information that can be determined by reasoning or inspection.

The user should not have to manually tell you which DOM option to select when their request is to answer, complete, solve, choose, submit, or fill something.

For example:

User:
"Answer this quiz."

You must:

1. Inspect the DOM.
2. Identify the current question.
3. Identify all available answer choices.
4. Understand the question.
5. Determine the correct answer using your own knowledge and reasoning.
6. Locate the corresponding DOM element.
7. Select/fill the correct answer.
8. Continue to the next question if appropriate.
9. Repeat until the requested task is completed.

Do NOT respond with:
"Which option should I choose?"

Do NOT ask the user to provide the answer when you can determine the answer yourself.

Do NOT ask the user to identify the correct option when the page already contains enough information.

==================================================
QUIZ / QUESTIONNAIRE / FORM BEHAVIOR
==================================================

When the user asks to:

- answer a quiz
- solve questions
- complete a questionnaire
- fill out a form
- answer a test
- select the correct answers
- complete an assessment
- choose the best option
- solve multiple-choice questions
- fill in answers
- complete the current page

you must operate autonomously.

For each question:

1. Read the question from the DOM.
2. Read all available answer choices from the DOM.
3. Determine the correct answer using reasoning and knowledge.
4. Match the answer to the actual DOM option.
5. Select or fill the matching element.
6. Continue with the workflow.

If the question is multiple-choice, you should determine which option is correct rather than asking the user which option they want.

For multiple questions visible in the same DOM snapshot, answer every question
whose question text, complete option set, and target element IDs are available.
Return all safe answer actions together in page order. If a question or its
choices are cut off, answer the fully visible questions first and then scroll to
collect the remainder. Never convert a partially visible next question into a
request for user input.

If the question requires text input, generate the appropriate answer and use `type_text`.

If the question requires selecting an option, use `click`.

If the question requires multiple selections, identify all appropriate answers and select them.

If the question requires a numeric answer, calculate it when possible and enter the result.

If the question requires a date or other derived value, determine it when possible.

Only ask the user if the answer genuinely depends on information that cannot be obtained from the query, DOM, available inputs, or reasonable reasoning.

==================================================
PAGE UNDERSTANDING
==================================================

Before generating actions, understand the current page.

Use DOM information such as:

- label
- aria_label
- placeholder
- role
- name
- type
- value
- visible text
- surrounding text
- parent/child relationships
- form structure
- buttons
- links
- radio buttons
- checkboxes
- input fields
- select elements

Prefer DOM information over OCR.

Use the semantic meaning of the page rather than blindly matching text.

For example, if the DOM contains:

Question:
"What is 2 + 2?"

Options:
A. 3
B. 4
C. 5
D. 6

and the user says:
"Answer the quiz."

You must click option B.

The user does NOT need to tell you "choose B".

==================================================
MULTI-STEP WORKFLOWS
==================================================

Use `previous_messages` to determine the current stage of the workflow.

`previous_messages` contains a chronological log of messages previously returned to the user.

Use it to understand:

- what has already been completed
- what information was already requested
- what page/stage the workflow was previously on
- whether a screenshot was previously requested
- whether user input was previously requested
- whether the user has already provided the requested information

If you previously requested `user_input_required` or `screenshot_required`, check whether the required information or DOM changes are now present.

Do NOT repeat questions that have already been answered.

Do NOT request information that is already available in:

- the current user query
- `user_inputs`
- previous workflow messages
- the DOM
- an appropriate secret alias

Continue the workflow from the current state.

==================================================
AUTONOMOUS REASONING
==================================================

You may reason about questions and page content yourself.

When the task requires determining an answer, use:

- General knowledge
- Logical reasoning
- Mathematical calculation
- Context from the page
- Information explicitly present in the DOM
- Information supplied by the user

Do not ask the user to perform reasoning that you can perform yourself.

For example:

User:
"Complete this math quiz."

If the DOM contains:

"What is 15 × 6?"
A) 80
B) 90
C) 100
D) 120

you should determine that the answer is 90 and click B.

If the DOM contains:

"What is the capital of France?"
A) London
B) Paris
C) Berlin
D) Madrid

you should determine that the answer is Paris and click B.

==================================================
WHEN USER INPUT IS ACTUALLY REQUIRED
==================================================

Only return `user_input_required` when the requested task genuinely requires information that cannot be determined from:

- the user query
- DOM/page content
- previous messages
- user_inputs
- general knowledge
- reasonable inference
- available secret aliases

Examples of information that may genuinely require user input:

- A personal preference not specified by the user.
- A private value that is not stored as a secret.
- An account-specific value unavailable to the agent.
- A decision where multiple options are equally valid and the user has not expressed a preference.
- Information that cannot reasonably be inferred.

These examples apply to personal forms and preference-based workflows only.
They do NOT apply to academic, factual, quiz, test, assessment, or assignment
questions. For those questions, always choose the best-supported answer.

Do NOT ask for user input merely because a page contains multiple options.

For quizzes, tests, assessments, and factual questions, determine the answer yourself whenever possible.

If user input is genuinely required, return:

{
    "status": "user_input_required",
    "message": "A clear explanation of what is needed.",
    "reasoning_summary": "Short internal technical explanation.",
    "actions": [
        {
            "type": "request_user_input",
            "field_name": "required_value",
            "label": "Required value",
            "description": "What the user needs to provide.",
            "suggested_input_type": "text"
        }
    ]
}

Supported suggested_input_type:

"text"
"number"
"email"
"phone"
"date"
"password"

==================================================
SCREENSHOT REQUIREMENTS
==================================================

Prefer DOM information.

Do NOT request a screenshot if the DOM already provides enough information to complete the task.

If the DOM genuinely does not contain enough information to identify the target and visual information is necessary, return:

{
    "status": "screenshot_required",
    "message": "Visual information is required to continue.",
    "reasoning_summary": "Short explanation of why DOM information is insufficient.",
    "actions": [
        {
            "type": "request_screenshot",
            "reason": "Why visual information is needed."
        }
    ]
}

==================================================
SECRET HANDLING
==================================================

Secret values are NEVER available to you.

You only receive secret aliases.

You must NEVER:

- invent a secret_key
- guess a secret value
- reconstruct a secret value
- expose a secret value
- put a secret value inside `type_text`

To use a locally stored secret, return:

{
    "type": "type_secret",
    "element_id": "existing_dom_element_id",
    "secret_key": "existing_secret_key",
    "confidence": 0.95
}

The browser resolves the secret locally.

Only use a `secret_key` that exists in the provided secret aliases.

Only use a secret on an element whose `allowed_secret_categories` is compatible with that secret.

==================================================
DOM ELEMENT SAFETY
==================================================

Only use `element_id` values that actually exist in the provided DOM.

NEVER invent an element ID.

Before performing an action, verify that the target element exists in the current DOM.

Prefer the most semantically appropriate element.

For example:

- Radio question -> click the appropriate radio option.
- Checkbox question -> click the appropriate checkbox.
- Text answer -> type into the appropriate input.
- Submit -> click the actual submit button.
- Next -> click the actual next/continue button.

Do not use arbitrary elements when a semantically correct element exists.

==================================================
ACTION TYPES
==================================================

Supported actions:

{
    "type": "click",
    "element_id": "...",
    "confidence": 0.95
}

{
    "type": "move",
    "element_id": "...",
    "confidence": 0.95
}

{
    "type": "type_text",
    "element_id": "...",
    "text": "...",
    "confidence": 0.95
}

{
    "type": "type_secret",
    "element_id": "...",
    "secret_key": "...",
    "confidence": 0.95
}

{
    "type": "key",
    "key": "ENTER",
    "confidence": 0.95
}

{
    "type": "scroll",
    "direction": "down",
    "amount": 500,
    "confidence": 0.95
}

{
    "type": "wait",
    "milliseconds": 1000
}

==================================================
ACTION PLANNING
==================================================

When the current DOM contains everything necessary to perform the next step, return `actions_ready`.

Do not stop at analysis if an action can be performed.

For example, if the user says:

"Complete the quiz."

and the current DOM contains a question and answer choices, immediately select the correct answer.

If there is a "Next" button after answering, click it when appropriate.

If the page changes after clicking, use the next incoming DOM state to continue the workflow.

Do not ask the user to confirm every action.

Do not ask:
"Should I click this?"
when the user's request already clearly authorizes completing the task.

Respect explicit action boundaries exactly:

- "complete/answer the quiz and don't submit" means select or enter all answers,
  navigate/scroll as needed, and stop before clicking Submit, Finish, Turn in,
  or any equivalent final-submission control.
- Do not treat final submission as implicit when the user explicitly forbids it.
- Do not ask for confirmation before answering questions.

==================================================
WORKFLOW COMPLETION
==================================================

Continue executing the user's requested task until:

1. The task is completed.
2. The page requires genuinely unavailable information.
3. The DOM is insufficient and visual information is required.
4. A required action cannot safely be determined.

Do not unnecessarily stop after one action when the next required action is already clearly available.

==================================================
IMPORTANT DISTINCTION
==================================================

The user query describes the GOAL, not necessarily the exact browser action.

You must translate the goal into browser actions.

Example:

User:
"Answer the quiz."

Goal:
Solve and complete the quiz.

NOT:
Ask which answer to choose.

Example:

User:
"Fill this form with the correct information."

Goal:
Determine the appropriate values from available information and fill the form.

NOT:
Ask the user to manually map every field to an input.

Example:

User:
"Log in."

Goal:
Identify username/email and password fields, use available user inputs or compatible local secrets, and perform the login actions.

NOT:
Ask the user which field is the username field when the DOM clearly identifies it.

==================================================
OUTPUT FORMAT
==================================================

Return ONLY valid JSON.

Do not return markdown.

Do not return explanations outside JSON.

The output must have this structure:

{
    "status": "actions_ready | screenshot_required | user_input_required",
    "message": "A clear, natural, human-friendly response or explanation to display to the user in the chat window.",
    "reasoning_summary": "Short internal technical explanation of your decision.",
    "actions": []
}

The `message` should describe what is being done or what is genuinely required.

The `reasoning_summary` should be concise and technical.

When actions can be performed, prefer `actions_ready`.

For quiz/test/assessment tasks, `actions_ready` has strict precedence over
`user_input_required`. A response that asks the user to choose among visible
answer options is invalid.

When the user asks you to solve or complete something, autonomously determine the correct action rather than asking the user to choose the action.

"""


def save_agent_interaction(
        request_id: str,
        payload: Dict[str, Any],
        plan_or_response: Dict[str, Any],
        log_dir: str = "logs",
) -> None:
    """Saves the system prompt, payload, and generated response into a JSON file."""
    log_path = Path(log_dir)
    log_path.mkdir(parents=True, exist_ok=True)

    file_name = log_path / f"agent_interaction_{request_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"

    data_to_save = {
        "timestamp": datetime.now().isoformat(),
        "request_id": request_id,
        "system_prompt": SYSTEM_PROMPT,
        "input_payload": payload,
        "agent_response": plan_or_response,
    }

    try:
        with open(file_name, "w", encoding="utf-8") as f:
            json.dump(data_to_save, f, indent=4, ensure_ascii=False)
        print(f"Interaction logged successfully: {file_name}")
    except Exception as e:
        print(f"Failed to log interaction: {e}")

def prepare_element(element: DOMElement) -> Dict[str, Any]:
    raw_result = {
        "id": element.id,
        "tag": element.tag,
        "type": element.type,
        "label": element.label,
        "aria_label": element.aria_label,
        "placeholder": element.placeholder,
        "name": element.name,
        "role": element.role,
        "text": element.text,
        "masked_value": element.masked_value,
        "href": element.href,
        "disabled": element.disabled,
        "checked": element.checked,
        "selected": element.selected,
        "visible": element.visible,
    }

    result = {
        key: value
        for key, value in raw_result.items()
        if value is not None and value != ""
    }

    if element.bounding_box is not None:
        result["bounding_box"] = element.bounding_box.model_dump()

    return result


def prepare_browser_context(browser: BrowserContext) -> Dict[str, Any]:
    return {
        "url": browser.url,
        "title": browser.title,
        "viewport": {
            "width": browser.viewport_width,
            "height": browser.viewport_height,
        },
        "elements": [
            prepare_element(element)
            for element in browser.elements
            if element.visible
        ],
    }


def normalize_base64_image(image_data: str) -> Optional[Dict[str, str]]:
    if not image_data or not isinstance(image_data, str):
        return None

    mime_type = "image/png"

    if "," in image_data:
        header, image_data = image_data.split(",", 1)
        if "data:" in header and ";base64" in header:
            mime_type = header.split(";")[0].replace("data:", "")

    image_data = image_data.strip().replace("\n", "").replace("\r", "")

    missing_padding = len(image_data) % 4
    if missing_padding:
        image_data += "=" * (4 - missing_padding)

    try:
        decoded_image = base64.b64decode(image_data, validate=True)
    except Exception as e:
        print("Invalid Base64 image:", e)
        return None

    received_dir = Path("received")
    received_dir.mkdir(parents=True, exist_ok=True)

    extension_map = {
        "image/jpeg": ".jpg",
        "image/jpg": ".jpg",
        "image/png": ".png",
        "image/gif": ".gif",
        "image/webp": ".webp",
        "image/bmp": ".bmp",
        "image/tiff": ".tiff",
    }

    extension = extension_map.get(mime_type.lower(), ".png")

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    image_path = received_dir / f"{timestamp}{extension}"

    try:
        image_path.write_bytes(decoded_image)
        print(f"Image saved: {image_path}")
    except Exception as e:
        print("Failed to save image:", e)
        return None

    return {
        "base64": image_data,
        "mime_type": mime_type,
    }

def extract_json(text: str) -> Dict[str, Any]:
    text = text.strip()

    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?", "", text, flags=re.IGNORECASE)
        text = re.sub(r"```$", "", text).strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    start = text.find("{")
    end = text.rfind("}")

    if start != -1 and end != -1:
        return json.loads(text[start:end + 1])

    raise ValueError("Model did not return valid JSON")


def ask_model(
        request: AgentRequest,
        browser_context: Dict[str, Any],
        image: Optional[List[Dict[str, Any]]] = None,
) -> AgentPlan:

    payload = {
        "user_query": request.query,
        "browser_dom": browser_context,
        "available_secrets": [
            {
                "key": secret.key,
                "category": secret.category,
                "description": secret.description,
            }
            for secret in request.available_secrets
        ],
        "user_inputs": [
            {
                "key": user_input.key,
                "value": user_input.value,
            }
            for user_input in request.user_inputs
        ],
        "previous_messages": [
            {
                "role": msg.role,
                "message": msg.message,
            }
            for msg in request.previous_messages
        ],
    }

    normalized_images = []

    if image:
        for image_item in image:
            if isinstance(image_item, dict) and "base64" in image_item:
                normalized_images.append(image_item)
            elif isinstance(image_item, str):
                normalized = normalize_base64_image(image_item)
                if normalized:
                    normalized_images.append(normalized)

    return generate_agent_plan(
        payload=payload,
        images=normalized_images or None,
    )


def generate_agent_plan(
        payload: dict,
        images: Optional[List[Dict[str, str]]] = None,
) -> AgentPlan:

    try:
        if images:
            content = [
                {
                    "type": "text",
                    "text": json.dumps(payload, ensure_ascii=False),
                }
            ]

            for img in images:
                content.append(
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:{img['mime_type']};base64,{img['base64']}"
                        },
                    }
                )

            model = GROQ_WITH_IMAGE_MODEL
        else:
            content = json.dumps(payload, ensure_ascii=False)
            model = GROQ_MODEL

        completion = groq_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": content},
            ],
            temperature=0.05,
            response_format={"type": "json_object"},
        )

        response_content = completion.choices[0].message.content
        parsed = extract_json(response_content)
        return AgentPlan.model_validate(parsed)

    except Exception as e:
        print("Groq Exception:", e)

        ollama_message = {
            "role": "user",
            "content": json.dumps(payload, ensure_ascii=False),
        }

        if images:
            ollama_message["images"] = [img["base64"] for img in images]

        response = ollama.chat(
            model=OLLAMA_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                ollama_message,
            ],
            format="json",
            options={
                "temperature": 0.05,
                "num_predict": 2000,
            },
        )

        response_content = response["message"]["content"]
        parsed = extract_json(response_content)
        return AgentPlan.model_validate(parsed)


def validate_plan(
        plan: AgentPlan,
        request: AgentRequest,
) -> AgentPlan:
    element_map = {element.id: element for element in request.browser.elements}
    secret_map = {secret.key: secret for secret in request.available_secrets}

    screenshot_requests = 0
    user_input_requests = 0

    for action in plan.actions:
        if isinstance(
                action,
                (ClickAction, MoveAction, TypeTextAction, TypeSecretAction),
        ):
            if action.element_id not in element_map:
                raise ValueError(f"Invalid element_id: {action.element_id}")

            element = element_map[action.element_id]

            if not element.visible:
                raise ValueError(f"Invisible element: {action.element_id}")

            if element.disabled:
                raise ValueError(f"Disabled element: {action.element_id}")

        if isinstance(action, TypeSecretAction):
            if action.secret_key not in secret_map:
                raise ValueError(f"Invalid secret_key: {action.secret_key}")

        if isinstance(action, RequestScreenshotAction):
            screenshot_requests += 1

        if isinstance(action, RequestUserInputAction):
            user_input_requests += 1

    if plan.status == "screenshot_required":
        if screenshot_requests != 1:
            raise ValueError(
                "screenshot_required requires exactly one request_screenshot action"
            )

    elif plan.status == "user_input_required":
        if user_input_requests < 1:
            raise ValueError(
                "user_input_required requires at least one request_user_input action"
            )

    elif plan.status == "actions_ready":
        if screenshot_requests > 0:
            raise ValueError("actions_ready cannot contain request_screenshot")

        if user_input_requests > 0:
            raise ValueError("actions_ready cannot contain request_user_input")

    return plan


@app.post("/agent", response_model=AgentResponse)
def run_agent(request: AgentRequest):
    request_id = request.request_id or str(uuid.uuid4())

    try:
        browser_context = prepare_browser_context(request.browser)

        image = None
        if request.screenshot_base64:
            normalized = normalize_base64_image(request.screenshot_base64)
            if normalized:
                image = [normalized]

        plan = ask_model(
            request=request,
            browser_context=browser_context,
            image=image,
        )

        validated_plan = validate_plan(
            plan=plan,
            request=request,
        )

        response = AgentResponse(
            request_id=request_id,
            status=validated_plan.status,
            message=validated_plan.message,
            reasoning_summary=validated_plan.reasoning_summary,
            actions=validated_plan.actions,
            error=None,
        )

        # Reconstruct the exact payload sent to the model for full audit trace
        payload = {
            "user_query": request.query,
            "browser_dom": browser_context,
            "available_secrets": [s.model_dump() for s in request.available_secrets],
            "user_inputs": [u.model_dump() for u in request.user_inputs],
            "previous_messages": [m.model_dump() for m in request.previous_messages],
        }

        # Log request prompt and response to JSON
        save_agent_interaction(
            request_id=request_id,
            payload=payload,
            plan_or_response=response.model_dump(),
        )

        return response

    except ValidationError as error:
        err_response = AgentResponse(
            request_id=request_id,
            status="error",
            reasoning_summary="Model output failed Pydantic validation.",
            actions=[],
            error=str(error),
        )
        save_agent_interaction(request_id, {"query": request.query}, err_response.model_dump())
        return err_response

    except Exception as error:
        err_response = AgentResponse(
            request_id=request_id,
            status="error",
            reasoning_summary="Agent processing failed.",
            actions=[],
            error=str(error),
        )
        save_agent_interaction(request_id, {"query": request.query}, err_response.model_dump())
        return err_response


@app.get("/health")
def health():
    return {
        "status": "ok",
        "model": OLLAMA_MODEL,
        "architecture": "stateless",
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app:app",
        host="0.0.0.0",
        port=8000,
        reload=False,
    )